Repository Yuridia850/API-GOOGLE, pull requests merged in 2025-08, with the labels that each got.

#51 Botón Eliminar
  calendar.html
  calendar.js
  calendary.css
Labels: enhancement

#54 Titulo-Evento-Css
  Img/T_logo.png
  calendary.css
Labels: documentation

#56 Fecha-Hora-Guardar_evento/cambios---fix_enlace_de_img.
  calendar.html
  calendary.css
Labels: enhancement

#62 Cambios_en_editar/crear_evento
  calendary.css
Labels: enhancement

#63 Se-arreglo-ordenamiento-scroll
  .vscode/settings.json
  calendar.js
  calendary.css
Labels: bug, enhancement

#65 Ultimo-arreglo-acomodar
  calendar.js
Labels: bug

#66 Progress bar
  calendar.html
  calendar.js
  calendary.css
Labels: enhancement

#67 agregando responsivo
  styles.css
Labels: enhancement

#68 Arreglo de botón
  styles.css
Labels: bug, enhancement

#69 Responsivo-calendario
  calendary.css
Labels: enhancement

#71 Bug fixes
  calendary.css
Labels: bug
